### ISSUE TITLE
undefined is not an object – in Safari

### ISSUE THREAD

**Issue by jvolker** [therewasaguy/p5js-webIDE#116] opened 2016-04-19 22:32 UTC
After pressing run with the starting code in Safari the browser console reports: `TypeError: undefined is not an object (evaluating 'sketchFrame.contentWindow.document')`

**Comment by therewasaguy** [comment] 2016-04-20 03:38
This is a duplicate of https://github.com/therewasaguy/p5js-webIDE/issues/50 so I'm going to close this but we can continue the discussion there. It should be a quick fix, and it's about time!

**Closed as completed by therewasaguy** 2016-04-20 03:38 UTC
